import { fileURLToPath } from "node:url";

/** The SQL migrations shipped with this package (generated by drizzle-kit, plus custom ones). */
export const migrationsFolder = fileURLToPath(new URL("../migrations", import.meta.url));
