import { sql } from "drizzle-orm";
import { EXPOSURE, VISIBILITY } from "@openhoard/core-policy";
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgSchema,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  unique,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { idPattern, type IdKind } from "./ids.js";

/*
 * The catalog's core tables (T-201). Conventions, which the tests in schema.test.ts and
 * rls.test.ts enforce:
 *
 * - Every table has `tenant_id` (the tenants table has `id`) and forced row-level security that
 *   matches it against `app.tenant_id`; see migrations/0001_tenant_rls.sql and database.ts.
 * - Primary keys and foreign keys include `tenant_id`, so a row can only ever reference rows of
 *   its own tenant. This holds even for code that runs without row-level security.
 * - Nothing cascades from a tenant, a zone or a blob. Removing a tenant's data is a deliberate,
 *   audited process (legal holds apply), never the side effect of one DELETE. Deleting an object
 *   does remove its versions and source references.
 * - Ids are generated by the application (ids.ts) and checked here, so a malformed or misplaced
 *   id fails loudly.
 * - Timestamps are `timestamptz`, read as Date objects; every connection runs in UTC.
 * - `bigint` columns use `mode: "number"` where values stay far below 2^53 (byte sizes).
 *
 * Changing this file? Run `pnpm --filter @openhoard/core-db db:generate` and commit the new
 * migration. CI fails when the schema and the migrations disagree.
 */

const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const quoted = (values: readonly string[]) => values.map((v) => `'${v}'`).join(", ");
const idCheck = (name: string, column: string, kind: IdKind) =>
  check(name, sql.raw(`${column} ~ '${idPattern(kind)}'`));

/** An organization. Everything else belongs to exactly one tenant. */
export const tenants = pgTable(
  "tenants",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    /**
     * Levels for a processed object none of whose tags sets one (core/policy resolveLevels).
     * Fail-closed until an admin or a pack says otherwise.
     */
    defaultVisibility: text("default_visibility", { enum: VISIBILITY }).notNull().default("hidden"),
    defaultExposure: text("default_exposure", { enum: EXPOSURE })
      .notNull()
      .default("metadata-only"),
    createdAt: createdAt(),
  },
  () => [
    idCheck("tenants_id_format", "id", "tenant"),
    check("tenants_name_length", sql`char_length(name) between 1 and 200`),
    check(
      "tenants_default_visibility_valid",
      sql.raw(`default_visibility in (${quoted(VISIBILITY)})`),
    ),
    check("tenants_default_exposure_valid", sql.raw(`default_exposure in (${quoted(EXPOSURE)})`)),
  ],
);

/** Where objects live and which rules apply to them (ADR and PRD: Managed, Indexed, Local-only, Code). */
export const zones = pgTable(
  "zones",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    kind: text("kind", { enum: ["managed", "indexed", "local-only", "code"] }).notNull(),
    name: text("name").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    unique("zones_name_unique").on(t.tenantId, t.name),
    idCheck("zones_id_format", "id", "zone"),
    check("zones_kind_valid", sql`kind in ('managed', 'indexed', 'local-only', 'code')`),
    check("zones_name_length", sql`char_length(name) between 1 and 200`),
  ],
);

/**
 * Immutable content, identified by its tenant-scoped BLAKE3 id (`b3t:…`, ADR-0013 and
 * core/catalog `scopedBlobId`). Identical bytes in one tenant are one blob; the raw content hash
 * is never stored, so the database cannot link identical files across tenants either.
 */
export const blobs = pgTable(
  "blobs",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    size: bigint("size", { mode: "number" }).notNull(),
    /** Storage key when OpenHoard holds the bytes (managed zones); null for index-only content. */
    location: text("location"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    check("blobs_id_format", sql`id ~ '^b3t:[0-9a-f]{64}$'`),
    check("blobs_size_nonnegative", sql`size >= 0`),
  ],
);

/** The logical file: what people and agents find, tag and share. */
export const objects = pgTable(
  "objects",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    zoneId: text("zone_id").notNull(),
    title: text("title").notNull(),
    /** Principal that owns the object, e.g. `user:…`; identities arrive with E1 (T-101). */
    ownerId: text("owner_id").notNull(),
    createdAt: createdAt(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    /** Set when the source deletes the file; rows are kept for audit and undo. */
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    /**
     * What people who can't read the object see instead of its title, when the title itself is
     * sensitive ("Termination – J. Smith.docx" → "HR document"). A model proposes it, the owner
     * confirms, edits or clears it (T-603).
     */
    displayTitle: text("display_title"),
    /**
     * Who decided on the display title: `model:…` for a proposal, `user:…` once a person
     * confirmed, edited or cleared it (a null display title then means the real one is fine).
     */
    displayTitleBy: text("display_title_by"),
    /** The title that decision was made for. After a rename it is stale and models may propose again. */
    displayTitleFor: text("display_title_for"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "objects_zone_fk",
      columns: [t.tenantId, t.zoneId],
      foreignColumns: [zones.tenantId, zones.id],
    }),
    index("objects_zone_idx").on(t.tenantId, t.zoneId),
    // A person's own files, and ownership checks by principal.
    index("objects_owner_idx").on(t.tenantId, t.ownerId),
    idCheck("objects_id_format", "id", "object"),
    check("objects_title_length", sql`char_length(title) between 1 and 1024`),
    check("objects_owner_principal", sql`owner_id ~ '^[a-z]+:.+$'`),
    check(
      "objects_display_title_length",
      sql`display_title is null or char_length(display_title) between 1 and 1024`,
    ),
    check(
      "objects_display_title_by",
      sql`display_title_by is null or display_title_by ~ '^(user|model):.+$'`,
    ),
    check(
      "objects_display_title_has_author",
      sql`display_title is null or display_title_by is not null`,
    ),
    check(
      "objects_display_title_decision",
      sql`(display_title_by is null) = (display_title_for is null)`,
    ),
  ],
);

/** One saved state of an object, pointing at an immutable blob. */
export const versions = pgTable(
  "versions",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    objectId: text("object_id").notNull(),
    /** 1, 2, 3… per object. */
    seq: integer("seq").notNull(),
    blobId: text("blob_id").notNull(),
    /** Media type essence in lower case, without parameters: `text/csv`, not `text/csv; charset=…`. */
    mime: text("mime").notNull(),
    /** Principal that saved this version, when the source says. */
    authorId: text("author_id"),
    /** The source's own version marker (e.g. a SharePoint cTag), to skip unchanged files. */
    sourceVersion: text("source_version"),
    /**
     * When enrichment finished tagging this content. Until then the object is treated as
     * unprocessed (core/policy UNPROCESSED: hidden, metadata-only), whatever its tags say.
     */
    processedAt: timestamp("processed_at", { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    unique("versions_seq_unique").on(t.tenantId, t.objectId, t.seq),
    foreignKey({
      name: "versions_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "versions_blob_fk",
      columns: [t.tenantId, t.blobId],
      foreignColumns: [blobs.tenantId, blobs.id],
    }),
    index("versions_blob_idx").on(t.tenantId, t.blobId),
    idCheck("versions_id_format", "id", "version"),
    check("versions_seq_positive", sql`seq > 0`),
    check(
      "versions_mime_format",
      sql`mime ~ '^[a-z0-9][a-z0-9!#$&^_.+-]*/[a-z0-9][a-z0-9!#$&^_.+-]*$'`,
    ),
    check("versions_author_principal", sql`author_id is null or author_id ~ '^[a-z]+:.+$'`),
    check(
      "versions_processed_after_creation",
      sql`processed_at is null or processed_at >= created_at`,
    ),
  ],
);

/**
 * Where an object comes from outside OpenHoard: a SharePoint drive item, a bucket key, a path.
 * `source` names the configured connection (connector instances arrive with E3, T-301); the
 * pair (source, external_id) identifies the item there, so re-crawls find the same object.
 */
export const sourceRefs = pgTable(
  "source_refs",
  {
    tenantId: text("tenant_id").notNull(),
    source: text("source").notNull(),
    externalId: text("external_id").notNull(),
    objectId: text("object_id").notNull(),
    url: text("url"),
    /** The source's change marker for the item (e.g. an eTag), for delta sync. */
    etag: text("etag"),
    syncedAt: timestamp("synced_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.source, t.externalId] }),
    foreignKey({
      name: "source_refs_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    index("source_refs_object_idx").on(t.tenantId, t.objectId),
    check("source_refs_source_format", sql`source ~ '^[a-z0-9][a-z0-9._-]{0,63}$'`),
    check("source_refs_external_id_length", sql`char_length(external_id) between 1 and 2048`),
  ],
);

/*
 * Tags (T-202). A tag is `facet:value`, e.g. `client:acme` or `sensitivity:restricted`. The
 * vocabulary (facets and their values) belongs to the tenant; values carry the visibility and
 * exposure levels core/policy resolves per object. Both parts are ASCII slugs, so a tag can sit
 * inside a principal (`tag:client:acme`) and compare the same on every engine (spike S2).
 */

const SLUG = "^[a-z0-9][a-z0-9._-]{0,127}$";

/** A dimension of the vocabulary: client, project, sensitivity, department… */
export const facets = pgTable(
  "facets",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    key: text("key").notNull(),
    label: text("label").notNull(),
    /**
     * Whether this facet's tags may be shown to people who can't read an object, on its
     * title-only card (e.g. `department`, `kind`; never `client`).
     */
    public: boolean("public").notNull().default(false),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.key] }),
    check("facets_key_format", sql`key ~ '^[a-z][a-z0-9-]{0,63}$'`),
    check("facets_label_length", sql`char_length(label) between 1 and 200`),
  ],
);

/**
 * One value of a facet. Proposed values (by a model, an agent or a user) start unapproved and
 * wait in the review inbox (T-406); nothing creates approved vocabulary implicitly.
 */
export const facetValues = pgTable(
  "facet_values",
  {
    tenantId: text("tenant_id").notNull(),
    facet: text("facet").notNull(),
    value: text("value").notNull(),
    label: text("label").notNull(),
    approved: boolean("approved").notNull().default(false),
    /** Null: this value sets no visibility; the object's other tags or the tenant default do. */
    visibility: text("visibility", { enum: VISIBILITY }),
    /** Null: this value sets no exposure level. */
    exposure: text("exposure", { enum: EXPOSURE }),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.facet, t.value] }),
    foreignKey({
      name: "facet_values_facet_fk",
      columns: [t.tenantId, t.facet],
      foreignColumns: [facets.tenantId, facets.key],
    }),
    check("facet_values_value_format", sql.raw(`value ~ '${SLUG}'`)),
    check("facet_values_label_length", sql`char_length(label) between 1 and 200`),
    check(
      "facet_values_visibility_valid",
      sql.raw(`visibility is null or visibility in (${quoted(VISIBILITY)})`),
    ),
    check(
      "facet_values_exposure_valid",
      sql.raw(`exposure is null or exposure in (${quoted(EXPOSURE)})`),
    ),
  ],
);

export const TAG_SOURCES = ["rule", "model", "user", "pack"] as const;

/** A tag on an object, with where it came from and whether a person has confirmed it. */
export const objectTags = pgTable(
  "object_tags",
  {
    tenantId: text("tenant_id").notNull(),
    objectId: text("object_id").notNull(),
    facet: text("facet").notNull(),
    value: text("value").notNull(),
    /** What applied it: a rule, a model, a person, or a pack. */
    source: text("source", { enum: TAG_SOURCES }).notNull(),
    /** Who or what exactly, when known: `user:…`, `model:…`, `rule:…`, `pack:…`. */
    appliedBy: text("applied_by"),
    /** 1 for rules, people and packs; the model's score otherwise. */
    confidence: real("confidence").notNull(),
    reviewed: boolean("reviewed").notNull().default(false),
    /**
     * A model proposed this tag first, and a rule or pack took it over (so grants match it): the
     * model's applier and confidence. When the rule stops giving the tag, it goes back to being
     * the model's unreviewed tag, which still tightens visibility, rather than disappearing.
     */
    modelAppliedBy: text("model_applied_by"),
    modelConfidence: real("model_confidence"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.objectId, t.facet, t.value] }),
    foreignKey({
      name: "object_tags_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "object_tags_value_fk",
      columns: [t.tenantId, t.facet, t.value],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    // Finding objects by tag: the search filter and "who can see this" (T-504, T-606).
    index("object_tags_tag_idx").on(t.tenantId, t.facet, t.value),
    check("object_tags_source_valid", sql.raw(`source in (${quoted(TAG_SOURCES)})`)),
    check("object_tags_confidence_range", sql`confidence >= 0 and confidence <= 1`),
    check(
      "object_tags_applied_by_principal",
      sql`applied_by is null or applied_by ~ '^[a-z]+:.+$'`,
    ),
    // A model's tag can't be recorded as a person's: the applier is of the source's kind.
    check(
      "object_tags_applied_by_matches_source",
      sql`applied_by is null or starts_with(applied_by, source || ':')`,
    ),
    // Provenance only on a rule's or pack's tag, a model's applier, and a confidence with it.
    check(
      "object_tags_model_provenance",
      sql`(model_confidence is null and model_applied_by is null)
       or (source in ('rule', 'pack') and model_confidence >= 0 and model_confidence <= 1
           and (model_applied_by is null or model_applied_by ~ '^model:.+$'))`,
    ),
  ],
);

/*
 * People and groups (T-101). Users come from the tenant's identity provider over SCIM (T-103)
 * or are created in OpenHoard, by invitation or an admin (T-108, T-110): `source` records which,
 * and only that side may change them (core/identity enforces it). Their principal is
 * `user:<id>`, a group's `group:<id>`, so a rename never breaks a grant.
 *
 * A user is active unless something stops them, and the stops are independent, so lifting one
 * never lifts another:
 *
 * - an admin lock (`user:` or `system:`), for an investigation or an emergency;
 * - a provider disable (`scim:`), when the identity provider deactivates the user;
 * - retirement, which is final: the person left or the account was deleted upstream. It frees
 *   the email for someone new. Rows are never deleted: users own objects and appear in audit.
 */
export const IDENTITY_SOURCES = ["scim", "local"] as const;
export const USER_KINDS = ["member", "guest"] as const;

export const users = pgTable(
  "users",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    email: text("email").notNull(),
    /** The email normalized for matching (core/identity emailKey()). */
    emailKey: text("email_key").notNull(),
    displayName: text("display_name").notNull(),
    /** Guests are people outside the organization: they never discover files (T-603). */
    kind: text("kind", { enum: USER_KINDS }).notNull().default("member"),
    source: text("source", { enum: IDENTITY_SOURCES }).notNull(),
    /** The identity provider's id for the user (SCIM externalId); always null for local users. */
    externalId: text("external_id"),
    createdAt: createdAt(),
    lockedAt: timestamp("locked_at", { withTimezone: true }),
    lockedBy: text("locked_by"),
    providerDisabledAt: timestamp("provider_disabled_at", { withTimezone: true }),
    providerDisabledBy: text("provider_disabled_by"),
    retiredAt: timestamp("retired_at", { withTimezone: true }),
    retiredBy: text("retired_by"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    // Among current users only: a retired address can belong to someone new.
    uniqueIndex("users_email_unique")
      .on(t.tenantId, t.emailKey)
      .where(sql`retired_at is null`),
    uniqueIndex("users_external_id_unique")
      .on(t.tenantId, t.externalId)
      .where(sql`external_id is not null and retired_at is null`),
    idCheck("users_id_format", "id", "user"),
    check("users_email_length", sql`char_length(email) between 3 and 320`),
    check("users_email_key_length", sql`char_length(email_key) between 3 and 320`),
    check("users_display_name_length", sql`char_length(display_name) between 1 and 256`),
    check("users_kind_valid", sql.raw(`kind in (${quoted(USER_KINDS)})`)),
    check("users_source_valid", sql.raw(`source in (${quoted(IDENTITY_SOURCES)})`)),
    check(
      "users_external_id_length",
      sql`external_id is null or char_length(external_id) between 1 and 512`,
    ),
    // An external id is the identity provider's: only SCIM users have one.
    check("users_external_id_scim", sql`source = 'scim' or external_id is null`),
    check("users_lock_complete", sql`(locked_at is null) = (locked_by is null)`),
    check("users_locked_by_admin", sql`locked_by is null or locked_by ~ '^(user|system):.+$'`),
    check(
      "users_provider_disabled_complete",
      sql`(provider_disabled_at is null) = (provider_disabled_by is null)`,
    ),
    check(
      "users_provider_disabled_by_scim",
      sql`provider_disabled_by is null or (provider_disabled_by ~ '^scim:.+$' and source = 'scim')`,
    ),
    check("users_retired_complete", sql`(retired_at is null) = (retired_by is null)`),
    check(
      "users_retired_by_principal",
      sql`retired_by is null or retired_by ~ '^(user|system|scim):.+$'`,
    ),
  ],
);

export const groups = pgTable(
  "groups",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    /** Display name; not unique, identity providers allow duplicates. */
    name: text("name").notNull(),
    source: text("source", { enum: IDENTITY_SOURCES }).notNull(),
    /** The identity provider's id for the group (SCIM externalId); always null for local groups. */
    externalId: text("external_id"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    uniqueIndex("groups_external_id_unique")
      .on(t.tenantId, t.externalId)
      .where(sql`external_id is not null`),
    idCheck("groups_id_format", "id", "group"),
    check("groups_name_length", sql`char_length(name) between 1 and 256`),
    check("groups_source_valid", sql.raw(`source in (${quoted(IDENTITY_SOURCES)})`)),
    check(
      "groups_external_id_length",
      sql`external_id is null or char_length(external_id) between 1 and 512`,
    ),
    check("groups_external_id_scim", sql`source = 'scim' or external_id is null`),
  ],
);

/**
 * How a user signs in: an OpenID Connect issuer and the subject it gives them (T-102, T-109), or
 * OpenHoard's own issuer for passkeys and email links (T-108). Sign-in matches on this pair,
 * never on email. Retiring a user removes their identities, so the pair can be linked anew.
 */
export const userIdentities = pgTable(
  "user_identities",
  {
    tenantId: text("tenant_id").notNull(),
    /** The issuer URL, e.g. `https://login.microsoftonline.com/<tid>/v2.0`. */
    issuer: text("issuer").notNull(),
    subject: text("subject").notNull(),
    userId: text("user_id").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.issuer, t.subject] }),
    foreignKey({
      name: "user_identities_user_fk",
      columns: [t.tenantId, t.userId],
      foreignColumns: [users.tenantId, users.id],
    }),
    index("user_identities_user_idx").on(t.tenantId, t.userId),
    check("user_identities_issuer_length", sql`char_length(issuer) between 1 and 1024`),
    check("user_identities_subject_length", sql`char_length(subject) between 1 and 512`),
  ],
);

/** Who is in which group. Direct membership only; nested groups arrive with SCIM (T-103). */
export const groupMembers = pgTable(
  "group_members",
  {
    tenantId: text("tenant_id").notNull(),
    groupId: text("group_id").notNull(),
    userId: text("user_id").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.groupId, t.userId] }),
    foreignKey({
      name: "group_members_group_fk",
      columns: [t.tenantId, t.groupId],
      foreignColumns: [groups.tenantId, groups.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "group_members_user_fk",
      columns: [t.tenantId, t.userId],
      foreignColumns: [users.tenantId, users.id],
    }),
    index("group_members_user_idx").on(t.tenantId, t.userId),
  ],
);

/*
 * Grants (T-602): who may read or write what, as data (spike S3). A grant gives a principal, a
 * user or a group, access to every object carrying a tag, or to one object. Grants expire by
 * default; the expiry is checked when grants are read, so an expired grant stops working the
 * moment it expires, with no job to run. Revoking keeps the row, for "why could X see this?".
 *
 * History has two limits: a grant on an object goes when the object is hard-deleted (objects are
 * normally soft-deleted), and a vocabulary value that was ever granted cannot be deleted, only
 * merged into another (T-406), which carries its grants along.
 */
export const GRANT_ROLES = ["read", "write"] as const;

export const grants = pgTable(
  "grants",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    /** `user:<id>` or `group:<id>`. */
    principal: text("principal").notNull(),
    role: text("role", { enum: GRANT_ROLES }).notNull(),
    /** A tag grant names a facet and value; an object grant names an object. Exactly one. */
    facet: text("facet"),
    value: text("value"),
    objectId: text("object_id"),
    grantedBy: text("granted_by").notNull(),
    createdAt: createdAt(),
    /** Null only for a grant made permanent on purpose. */
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: text("revoked_by"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "grants_tag_fk",
      columns: [t.tenantId, t.facet, t.value],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    foreignKey({
      name: "grants_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    // Loading a caller's grants: by principal, live ones first.
    index("grants_principal_idx").on(t.tenantId, t.principal),
    index("grants_object_idx").on(t.tenantId, t.objectId),
    // "Who can see this?" by tag (T-606), and merging a value (T-406) carrying its grants.
    index("grants_tag_idx")
      .on(t.tenantId, t.facet, t.value)
      .where(sql`facet is not null`),
    idCheck("grants_id_format", "id", "grant"),
    check("grants_principal_format", sql`principal ~ '^(user|group):.+$'`),
    check("grants_role_valid", sql.raw(`role in (${quoted(GRANT_ROLES)})`)),
    check(
      "grants_one_target",
      sql`(facet is not null and value is not null and object_id is null)
       or (facet is null and value is null and object_id is not null)`,
    ),
    check("grants_granted_by_principal", sql`granted_by ~ '^[a-z]+:.+$'`),
    check("grants_expiry_after_creation", sql`expires_at is null or expires_at > created_at`),
    check("grants_revoked_after_creation", sql`revoked_at is null or revoked_at >= created_at`),
    check(
      "grants_revocation_complete",
      sql`(revoked_at is null and revoked_by is null)
       or (revoked_at is not null and revoked_by is not null and revoked_by ~ '^[a-z]+:.+$')`,
    ),
  ],
);

/*
 * The review inbox (T-406). A tag that must not apply on its own waits here instead of in
 * object_tags: a value not yet in the approved vocabulary, a model's low-confidence guess, or a
 * model setting a value that carries visibility or exposure levels. A person approves (the tag
 * applies, reviewed, and a new value joins the vocabulary), rejects, or merges it into an
 * existing value. Resolved items stay, as the record of who decided.
 */
export const REVIEW_REASONS = ["new-value", "low-confidence", "sensitive"] as const;
/** `withdrawn`: a rule's item, closed when the rule stopped giving the tag before anyone decided. */
export const REVIEW_DECISIONS = ["approved", "rejected", "merged", "withdrawn"] as const;

export const tagReviews = pgTable(
  "tag_reviews",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    objectId: text("object_id").notNull(),
    facet: text("facet").notNull(),
    value: text("value").notNull(),
    reason: text("reason", { enum: REVIEW_REASONS }).notNull(),
    source: text("source", { enum: TAG_SOURCES }).notNull(),
    appliedBy: text("applied_by"),
    confidence: real("confidence").notNull(),
    createdAt: createdAt(),
    decision: text("decision", { enum: REVIEW_DECISIONS }),
    /** For a merge: the approved value the tag was applied as instead. */
    mergedInto: text("merged_into"),
    resolvedBy: text("resolved_by"),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "tag_reviews_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "tag_reviews_value_fk",
      columns: [t.tenantId, t.facet, t.value],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    foreignKey({
      name: "tag_reviews_merged_fk",
      columns: [t.tenantId, t.facet, t.mergedInto],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    // The inbox (listOpenReviews): open items, oldest first, in its exact order.
    index("tag_reviews_open_idx")
      .on(t.tenantId, t.createdAt, t.id)
      .where(sql`resolved_at is null`),
    // Open items for a tag: what approving or merging a value resolves.
    index("tag_reviews_tag_idx")
      .on(t.tenantId, t.facet, t.value)
      .where(sql`resolved_at is null`),
    // An object's items, open or resolved (and the cascade when the object is deleted).
    index("tag_reviews_object_idx").on(t.tenantId, t.objectId),
    // One open item per object and tag, however often it is proposed.
    uniqueIndex("tag_reviews_one_open")
      .on(t.tenantId, t.objectId, t.facet, t.value)
      .where(sql`resolved_at is null`),
    idCheck("tag_reviews_id_format", "id", "review"),
    check("tag_reviews_reason_valid", sql.raw(`reason in (${quoted(REVIEW_REASONS)})`)),
    check("tag_reviews_source_valid", sql.raw(`source in (${quoted(TAG_SOURCES)})`)),
    check("tag_reviews_confidence_range", sql`confidence >= 0 and confidence <= 1`),
    check(
      "tag_reviews_applied_by_principal",
      sql`applied_by is null or applied_by ~ '^[a-z]+:.+$'`,
    ),
    check(
      "tag_reviews_applied_by_matches_source",
      sql`applied_by is null or starts_with(applied_by, source || ':')`,
    ),
    check(
      "tag_reviews_resolution_complete",
      sql.raw(`(decision is null and resolved_by is null and resolved_at is null and merged_into is null)
       or (decision is not null and decision in (${quoted(REVIEW_DECISIONS)})
           and resolved_by is not null and resolved_by ~ '^[a-z]+:.+$'
           and resolved_at is not null and resolved_at >= created_at
           and (decision = 'merged') = (merged_into is not null))`),
    ),
  ],
);

/** The tag string policy and search use for a facet and value. */
export const tagOf = (facet: string, value: string): string => `${facet}:${value}`;

/**
 * Packs applied to a tenant (T-607): declarative facets, values, defaults, tag rules and Cedar
 * policies. `content` is the pack as applied, the source of its rules and policies; the
 * vocabulary it created lives in facets and facet_values like any other.
 */
export const tenantPacks = pgTable(
  "tenant_packs",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    name: text("name").notNull(),
    version: text("version").notNull(),
    content: jsonb("content").notNull(),
    /** SHA-256 of the pack's canonical JSON, as reviewed. */
    contentHash: text("content_hash").notNull(),
    appliedBy: text("applied_by").notNull(),
    appliedAt: timestamp("applied_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.name] }),
    check("tenant_packs_name_format", sql`name ~ '^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$'`),
    check("tenant_packs_version_length", sql`char_length(version) between 5 and 64`),
    check("tenant_packs_hash_format", sql`content_hash ~ '^[0-9a-f]{64}$'`),
    check("tenant_packs_applied_by_principal", sql`applied_by ~ '^[a-z]+:.+$'`),
  ],
);

/*
 * Audit (T-701): one append-only, hash-chained log per tenant, in its own schema. core/audit
 * appends and verifies; the chain rules are in core/audit/src/chain.ts.
 *
 * `event` is the exact canonical JSON the hash covers, so verification never depends on how the
 * database round-trips a type. The other columns repeat its fields for queries and exports.
 * Rows can be read and inserted in their tenant, never changed: see 0005_audit_rls.sql. Every
 * insert must extend the chain with a row that checks out (0017_audit_check_event.sql).
 */
export const auditSchema = pgSchema("audit");

const HASH = "^[0-9a-f]{64}$";

export const auditEvents = auditSchema.table(
  "events",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    seq: bigint("seq", { mode: "number" }).notNull(),
    at: timestamp("at", { withTimezone: true }).notNull(),
    actor: text("actor").notNull(),
    action: text("action").notNull(),
    decision: text("decision", { enum: ["allow", "deny"] }).notNull(),
    client: text("client"),
    object: text("object"),
    version: text("version"),
    event: text("event").notNull(),
    prevHash: text("prev_hash").notNull(),
    hash: text("hash").notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.seq] }),
    // Exports filter by time, actor and object (T-703).
    index("audit_events_at_idx").on(t.tenantId, t.at),
    index("audit_events_object_idx").on(t.tenantId, t.object),
    index("audit_events_actor_idx").on(t.tenantId, t.actor, t.seq),
    check("audit_events_seq_positive", sql`seq > 0`),
    check("audit_events_decision_valid", sql`decision in ('allow', 'deny')`),
    check("audit_events_hash_format", sql.raw(`hash ~ '${HASH}' and prev_hash ~ '${HASH}'`)),
  ],
);

/** Every table in the public schema, for tests and tooling that must cover all of them. */
export const tables = {
  tenants,
  zones,
  blobs,
  objects,
  versions,
  sourceRefs,
  facets,
  facetValues,
  objectTags,
  grants,
  tagReviews,
  users,
  userIdentities,
  groups,
  groupMembers,
  tenantPacks,
} as const;
