import { sql } from "drizzle-orm";
import { EXPOSURE, VISIBILITY, type ClientTrust } from "@openhoard/core-policy";
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  jsonb,
  pgSchema,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  unique,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { idPattern, type IdKind } from "./ids.js";

/*
 * The catalog's core tables (T-201). Conventions, which the tests in schema.test.ts and
 * rls.test.ts enforce:
 *
 * - Every table has `tenant_id` (the tenants table has `id`) and forced row-level security that
 *   matches it against `app.tenant_id`; see migrations/0001_tenant_rls.sql and database.ts.
 * - Primary keys and foreign keys include `tenant_id`, so a row can only ever reference rows of
 *   its own tenant. This holds even for code that runs without row-level security.
 * - Nothing cascades from a tenant, a zone or a blob. Removing a tenant's data is a deliberate,
 *   audited process (legal holds apply), never the side effect of one DELETE. Deleting an object
 *   does remove its versions and source references.
 * - Ids are generated by the application (ids.ts) and checked here, so a malformed or misplaced
 *   id fails loudly.
 * - Timestamps are `timestamptz`, read as Date objects; every connection runs in UTC.
 * - `bigint` columns use `mode: "number"` where values stay far below 2^53 (byte sizes).
 *
 * Changing this file? Run `pnpm --filter @openhoard/core-db db:generate` and commit the new
 * migration. CI fails when the schema and the migrations disagree.
 */

const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const quoted = (values: readonly string[]) => values.map((v) => `'${v}'`).join(", ");
const idCheck = (name: string, column: string, kind: IdKind) =>
  check(name, sql.raw(`${column} ~ '${idPattern(kind)}'`));

/** An organization. Everything else belongs to exactly one tenant. */
export const tenants = pgTable(
  "tenants",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    /**
     * Levels for a processed object none of whose tags sets one (core/policy resolveLevels).
     * Fail-closed until an admin or a pack says otherwise.
     */
    defaultVisibility: text("default_visibility", { enum: VISIBILITY }).notNull().default("hidden"),
    defaultExposure: text("default_exposure", { enum: EXPOSURE })
      .notNull()
      .default("metadata-only"),
    createdAt: createdAt(),
  },
  () => [
    idCheck("tenants_id_format", "id", "tenant"),
    check("tenants_name_length", sql`char_length(name) between 1 and 200`),
    check(
      "tenants_default_visibility_valid",
      sql.raw(`default_visibility in (${quoted(VISIBILITY)})`),
    ),
    check("tenants_default_exposure_valid", sql.raw(`default_exposure in (${quoted(EXPOSURE)})`)),
  ],
);

/** What a zone is (Dev Plan zones): what `resource.zone` is to authorize(). */
export const ZONE_KINDS = ["managed", "indexed", "local-only", "code"] as const;

/** Where objects live and which rules apply to them (ADR and PRD: Managed, Indexed, Local-only, Code). */
export const zones = pgTable(
  "zones",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    kind: text("kind", { enum: ZONE_KINDS }).notNull(),
    name: text("name").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    unique("zones_name_unique").on(t.tenantId, t.name),
    idCheck("zones_id_format", "id", "zone"),
    check("zones_kind_valid", sql`kind in ('managed', 'indexed', 'local-only', 'code')`),
    check("zones_name_length", sql`char_length(name) between 1 and 200`),
  ],
);

/**
 * Immutable content, identified by its tenant-scoped BLAKE3 id (`b3t:…`, ADR-0013 and
 * core/catalog `scopedBlobId`). Identical bytes in one tenant are one blob; the raw content hash
 * is never stored, so the database cannot link identical files across tenants either.
 */
export const blobs = pgTable(
  "blobs",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    size: bigint("size", { mode: "number" }).notNull(),
    /** Storage key when OpenHoard holds the bytes (managed zones); null for index-only content. */
    location: text("location"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    check("blobs_id_format", sql`id ~ '^b3t:[0-9a-f]{64}$'`),
    check("blobs_size_nonnegative", sql`size >= 0`),
  ],
);

/** The logical file: what people and agents find, tag and share. */
export const objects = pgTable(
  "objects",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    zoneId: text("zone_id").notNull(),
    title: text("title").notNull(),
    /** Principal that owns the object, e.g. `user:…`; identities arrive with E1 (T-101). */
    ownerId: text("owner_id").notNull(),
    createdAt: createdAt(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    /** Set when the source deletes the file; rows are kept for audit and undo. */
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
    /**
     * What people who can't read the object see instead of its title, when the title itself is
     * sensitive ("Termination – J. Smith.docx" → "HR document"). A model proposes it, the owner
     * confirms, edits or clears it (T-603).
     */
    displayTitle: text("display_title"),
    /**
     * Who decided on the display title: `model:…` for a proposal, `user:…` once a person
     * confirmed, edited or cleared it (a null display title then means the real one is fine).
     */
    displayTitleBy: text("display_title_by"),
    /** The title that decision was made for. After a rename it is stale and models may propose again. */
    displayTitleFor: text("display_title_for"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "objects_zone_fk",
      columns: [t.tenantId, t.zoneId],
      foreignColumns: [zones.tenantId, zones.id],
    }),
    index("objects_zone_idx").on(t.tenantId, t.zoneId),
    // A person's own files, and ownership checks by principal.
    index("objects_owner_idx").on(t.tenantId, t.ownerId),
    idCheck("objects_id_format", "id", "object"),
    check("objects_title_length", sql`char_length(title) between 1 and 1024`),
    check("objects_owner_principal", sql`owner_id ~ '^[a-z]+:.+$'`),
    check(
      "objects_display_title_length",
      sql`display_title is null or char_length(display_title) between 1 and 1024`,
    ),
    check(
      "objects_display_title_by",
      sql`display_title_by is null or display_title_by ~ '^(user|model):.+$'`,
    ),
    check(
      "objects_display_title_has_author",
      sql`display_title is null or display_title_by is not null`,
    ),
    check(
      "objects_display_title_decision",
      sql`(display_title_by is null) = (display_title_for is null)`,
    ),
  ],
);

/** One saved state of an object, pointing at an immutable blob. */
export const versions = pgTable(
  "versions",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    objectId: text("object_id").notNull(),
    /** 1, 2, 3… per object. */
    seq: integer("seq").notNull(),
    blobId: text("blob_id").notNull(),
    /** Media type essence in lower case, without parameters: `text/csv`, not `text/csv; charset=…`. */
    mime: text("mime").notNull(),
    /** Principal that saved this version, when the source says. */
    authorId: text("author_id"),
    /** The source's own version marker (e.g. a SharePoint cTag), to skip unchanged files. */
    sourceVersion: text("source_version"),
    /**
     * When enrichment finished tagging this content. Until then the object is treated as
     * unprocessed (core/policy UNPROCESSED: hidden, metadata-only), whatever its tags say.
     */
    processedAt: timestamp("processed_at", { withTimezone: true }),
    /**
     * When enrichment gave up on this content, unprocessed, because a newer version replaced it
     * (core/catalog markSuperseded()). It never becomes current again, so nothing will enrich
     * it; `processed_at` stays null, since it never was.
     */
    supersededAt: timestamp("superseded_at", { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    unique("versions_seq_unique").on(t.tenantId, t.objectId, t.seq),
    // For foreign keys that name a version of a given object (activity_events).
    unique("versions_object_id_unique").on(t.tenantId, t.objectId, t.id),
    foreignKey({
      name: "versions_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "versions_blob_fk",
      columns: [t.tenantId, t.blobId],
      foreignColumns: [blobs.tenantId, blobs.id],
    }),
    index("versions_blob_idx").on(t.tenantId, t.blobId),
    // Versions enrichment hasn't finished and still may, for core/jobs' sweep (usually few).
    index("versions_pending_idx")
      .on(t.tenantId, t.objectId, t.seq)
      .where(sql`processed_at is null and superseded_at is null`),
    idCheck("versions_id_format", "id", "version"),
    check("versions_seq_positive", sql`seq > 0`),
    check(
      "versions_mime_format",
      sql`mime ~ '^[a-z0-9][a-z0-9!#$&^_.+-]*/[a-z0-9][a-z0-9!#$&^_.+-]*$'`,
    ),
    check("versions_author_principal", sql`author_id is null or author_id ~ '^[a-z]+:.+$'`),
    check(
      "versions_processed_after_creation",
      sql`processed_at is null or processed_at >= created_at`,
    ),
    check(
      "versions_superseded_unprocessed",
      sql`superseded_at is null or (processed_at is null and superseded_at >= created_at)`,
    ),
  ],
);

/**
 * Where an object comes from outside OpenHoard: a SharePoint drive item, a bucket key, a path.
 * `source` names the configured connection (connector instances arrive with E3, T-301); the
 * pair (source, external_id) identifies the item there, so re-crawls find the same object.
 */
export const sourceRefs = pgTable(
  "source_refs",
  {
    tenantId: text("tenant_id").notNull(),
    source: text("source").notNull(),
    externalId: text("external_id").notNull(),
    objectId: text("object_id").notNull(),
    url: text("url"),
    /** The source's change marker for the item (e.g. an eTag), for delta sync. */
    etag: text("etag"),
    syncedAt: timestamp("synced_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.source, t.externalId] }),
    foreignKey({
      name: "source_refs_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    index("source_refs_object_idx").on(t.tenantId, t.objectId),
    check("source_refs_source_format", sql`source ~ '^[a-z0-9][a-z0-9._-]{0,63}$'`),
    check("source_refs_external_id_length", sql`char_length(external_id) between 1 and 2048`),
  ],
);

/*
 * Tags (T-202). A tag is `facet:value`, e.g. `client:acme` or `sensitivity:restricted`. The
 * vocabulary (facets and their values) belongs to the tenant; values carry the visibility and
 * exposure levels core/policy resolves per object. Both parts are ASCII slugs, so a tag can sit
 * inside a principal (`tag:client:acme`) and compare the same on every engine (spike S2).
 */

const SLUG = "^[a-z0-9][a-z0-9._-]{0,127}$";

/** A dimension of the vocabulary: client, project, sensitivity, department… */
export const facets = pgTable(
  "facets",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    key: text("key").notNull(),
    label: text("label").notNull(),
    /**
     * Whether this facet's tags may be shown to people who can't read an object, on its
     * title-only card (e.g. `department`, `kind`; never `client`).
     */
    public: boolean("public").notNull().default(false),
    /**
     * At most one value of this facet per object (e.g. `sensitivity`): a second one waits in
     * review unless a person sets it, and replaces the first when it applies (T-409).
     */
    single: boolean("single").notNull().default(false),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.key] }),
    check("facets_key_format", sql`key ~ '^[a-z][a-z0-9-]{0,63}$'`),
    check("facets_label_length", sql`char_length(label) between 1 and 200`),
  ],
);

/**
 * One value of a facet. Proposed values (by a model, an agent or a user) start unapproved and
 * wait in the review inbox (T-406); nothing creates approved vocabulary implicitly.
 */
export const facetValues = pgTable(
  "facet_values",
  {
    tenantId: text("tenant_id").notNull(),
    facet: text("facet").notNull(),
    value: text("value").notNull(),
    label: text("label").notNull(),
    approved: boolean("approved").notNull().default(false),
    /** Null: this value sets no visibility; the object's other tags or the tenant default do. */
    visibility: text("visibility", { enum: VISIBILITY }),
    /** Null: this value sets no exposure level. */
    exposure: text("exposure", { enum: EXPOSURE }),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.facet, t.value] }),
    foreignKey({
      name: "facet_values_facet_fk",
      columns: [t.tenantId, t.facet],
      foreignColumns: [facets.tenantId, facets.key],
    }),
    check("facet_values_value_format", sql.raw(`value ~ '${SLUG}'`)),
    check("facet_values_label_length", sql`char_length(label) between 1 and 200`),
    check(
      "facet_values_visibility_valid",
      sql.raw(`visibility is null or visibility in (${quoted(VISIBILITY)})`),
    ),
    check(
      "facet_values_exposure_valid",
      sql.raw(`exposure is null or exposure in (${quoted(EXPOSURE)})`),
    ),
  ],
);

export const TAG_SOURCES = ["rule", "model", "user", "pack"] as const;

/** A tag on an object, with where it came from and whether a person has confirmed it. */
export const objectTags = pgTable(
  "object_tags",
  {
    tenantId: text("tenant_id").notNull(),
    objectId: text("object_id").notNull(),
    facet: text("facet").notNull(),
    value: text("value").notNull(),
    /** What applied it: a rule, a model, a person, or a pack. */
    source: text("source", { enum: TAG_SOURCES }).notNull(),
    /** Who or what exactly, when known: `user:…`, `model:…`, `rule:…`, `pack:…`. */
    appliedBy: text("applied_by"),
    /** 1 for rules, people and packs; the model's score otherwise. */
    confidence: real("confidence").notNull(),
    reviewed: boolean("reviewed").notNull().default(false),
    /**
     * A model proposed this tag first, and a rule or pack took it over (so grants match it): the
     * model's applier and confidence. When the rule stops giving the tag, it goes back to being
     * the model's unreviewed tag, which still tightens visibility, rather than disappearing.
     */
    modelAppliedBy: text("model_applied_by"),
    modelConfidence: real("model_confidence"),
    /**
     * Set on the object's primary tag, its home (T-409): who made it primary, `user:…` or
     * `rule:…`. At most one per object, and only on a trusted tag.
     */
    primaryBy: text("primary_by"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.objectId, t.facet, t.value] }),
    foreignKey({
      name: "object_tags_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "object_tags_value_fk",
      columns: [t.tenantId, t.facet, t.value],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    // Finding objects by tag: the search filter and "who can see this" (T-504, T-606).
    index("object_tags_tag_idx").on(t.tenantId, t.facet, t.value),
    check("object_tags_source_valid", sql.raw(`source in (${quoted(TAG_SOURCES)})`)),
    check("object_tags_confidence_range", sql`confidence >= 0 and confidence <= 1`),
    check(
      "object_tags_applied_by_principal",
      sql`applied_by is null or applied_by ~ '^[a-z]+:.+$'`,
    ),
    // A model's tag can't be recorded as a person's: the applier is of the source's kind.
    check(
      "object_tags_applied_by_matches_source",
      sql`applied_by is null or starts_with(applied_by, source || ':')`,
    ),
    // One primary tag per object, and never an unreviewed model guess: the home decides views,
    // paths and offboarding, so only a person, a rule or a pack sets it.
    uniqueIndex("object_tags_one_primary")
      .on(t.tenantId, t.objectId)
      .where(sql`primary_by is not null`),
    check(
      "object_tags_primary_trusted",
      sql`primary_by is null or (primary_by ~ '^(user|rule|pack):.+$' and (source <> 'model' or reviewed))`,
    ),
    // Provenance only on a rule's or pack's tag, a model's applier, and a confidence with it.
    check(
      "object_tags_model_provenance",
      sql`(model_confidence is null and model_applied_by is null)
       or (source in ('rule', 'pack') and model_confidence >= 0 and model_confidence <= 1
           and (model_applied_by is null or model_applied_by ~ '^model:.+$'))`,
    ),
  ],
);

/*
 * People and groups (T-101). Users come from the tenant's identity provider over SCIM (T-103)
 * or are created in OpenHoard, by invitation or an admin (T-108, T-110): `source` records which,
 * and only that side may change them (core/identity enforces it). Their principal is
 * `user:<id>`, a group's `group:<id>`, so a rename never breaks a grant.
 *
 * A user is active unless something stops them, and the stops are independent, so lifting one
 * never lifts another:
 *
 * - an admin lock (`user:` or `system:`), for an investigation or an emergency;
 * - a provider disable (`scim:`), when the identity provider deactivates the user;
 * - retirement, which is final: the person left or the account was deleted upstream. It frees
 *   the email for someone new. Rows are never deleted: users own objects and appear in audit.
 */
export const IDENTITY_SOURCES = ["scim", "local"] as const;
/** `service`: a service account (T-111), a machine that authenticates with API keys only. */
export const USER_KINDS = ["member", "guest", "service"] as const;

export const users = pgTable(
  "users",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    /** A person's address; a service account has none. */
    email: text("email"),
    /** The email normalized for matching (core/identity emailKey()). */
    emailKey: text("email_key"),
    displayName: text("display_name").notNull(),
    /** Guests are people outside the organization: they never discover files (T-603). */
    kind: text("kind", { enum: USER_KINDS }).notNull().default("member"),
    source: text("source", { enum: IDENTITY_SOURCES }).notNull(),
    /** The identity provider's id for the user (SCIM externalId); always null for local users. */
    externalId: text("external_id"),
    /**
     * The identity provider's sign-in name for the user (SCIM userName, Entra's UPN), as sent:
     * SCIM users only. Entra finds its users by it, so it is kept even when it isn't the email.
     */
    userName: text("user_name"),
    /** The userName as matched: Unicode NFC, lower case (core/identity userNameKey()). */
    userNameKey: text("user_name_key"),
    /** Name parts, as the identity provider sent them (SCIM name.givenName, name.familyName). */
    givenName: text("given_name"),
    familyName: text("family_name"),
    createdAt: createdAt(),
    lockedAt: timestamp("locked_at", { withTimezone: true }),
    lockedBy: text("locked_by"),
    providerDisabledAt: timestamp("provider_disabled_at", { withTimezone: true }),
    providerDisabledBy: text("provider_disabled_by"),
    retiredAt: timestamp("retired_at", { withTimezone: true }),
    retiredBy: text("retired_by"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    // Among current users only: a retired address can belong to someone new.
    uniqueIndex("users_email_unique")
      .on(t.tenantId, t.emailKey)
      .where(sql`retired_at is null`),
    uniqueIndex("users_external_id_unique")
      .on(t.tenantId, t.externalId)
      .where(sql`external_id is not null and retired_at is null`),
    idCheck("users_id_format", "id", "user"),
    check("users_email_length", sql`char_length(email) between 3 and 320`),
    check("users_email_key_length", sql`char_length(email_key) between 3 and 320`),
    check("users_display_name_length", sql`char_length(display_name) between 1 and 256`),
    check("users_kind_valid", sql.raw(`kind in (${quoted(USER_KINDS)})`)),
    // People have an email and service accounts don't; service accounts are OpenHoard's own.
    check(
      "users_service_email",
      sql`(kind = 'service') = (email is null) and (email is null) = (email_key is null)`,
    ),
    check("users_service_local", sql`kind <> 'service' or source = 'local'`),
    // For keys to name a service account in their foreign key (api_keys).
    unique("users_kind_unique").on(t.tenantId, t.id, t.kind),
    check("users_source_valid", sql.raw(`source in (${quoted(IDENTITY_SOURCES)})`)),
    check(
      "users_external_id_length",
      sql`external_id is null or char_length(external_id) between 1 and 512`,
    ),
    // An external id is the identity provider's: only SCIM users have one.
    check("users_external_id_scim", sql`source = 'scim' or external_id is null`),
    // A userName is unique among current users, compared by its key (SCIM: case-insensitive).
    uniqueIndex("users_user_name_unique")
      .on(t.tenantId, t.userNameKey)
      .where(sql`user_name_key is not null and retired_at is null`),
    check("users_user_name_scim", sql`source = 'scim' or user_name is null`),
    check(
      "users_user_name_complete",
      sql`(user_name is null) = (user_name_key is null)
       and (user_name is null or char_length(user_name) between 1 and 512)
       and (user_name_key is null or char_length(user_name_key) between 1 and 512)`,
    ),
    check(
      "users_name_parts_length",
      sql`(given_name is null or char_length(given_name) between 1 and 256)
       and (family_name is null or char_length(family_name) between 1 and 256)`,
    ),
    check("users_lock_complete", sql`(locked_at is null) = (locked_by is null)`),
    check("users_locked_by_admin", sql`locked_by is null or locked_by ~ '^(user|system):.+$'`),
    check(
      "users_provider_disabled_complete",
      sql`(provider_disabled_at is null) = (provider_disabled_by is null)`,
    ),
    check(
      "users_provider_disabled_by_scim",
      sql`provider_disabled_by is null or (provider_disabled_by ~ '^scim:.+$' and source = 'scim')`,
    ),
    check("users_retired_complete", sql`(retired_at is null) = (retired_by is null)`),
    check(
      "users_retired_by_principal",
      sql`retired_by is null or retired_by ~ '^(user|system|scim):.+$'`,
    ),
  ],
);

export const groups = pgTable(
  "groups",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    /** Display name; not unique, identity providers allow duplicates. */
    name: text("name").notNull(),
    source: text("source", { enum: IDENTITY_SOURCES }).notNull(),
    /** The identity provider's id for the group (SCIM externalId); always null for local groups. */
    externalId: text("external_id"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    uniqueIndex("groups_external_id_unique")
      .on(t.tenantId, t.externalId)
      .where(sql`external_id is not null`),
    idCheck("groups_id_format", "id", "group"),
    check("groups_name_length", sql`char_length(name) between 1 and 256`),
    check("groups_source_valid", sql.raw(`source in (${quoted(IDENTITY_SOURCES)})`)),
    check(
      "groups_external_id_length",
      sql`external_id is null or char_length(external_id) between 1 and 512`,
    ),
    check("groups_external_id_scim", sql`source = 'scim' or external_id is null`),
  ],
);

/**
 * How a user signs in: an OpenID Connect issuer and the subject it gives them (T-102, T-109), or
 * OpenHoard's own issuer for passkeys and email links (T-108). Sign-in matches on this pair,
 * never on email. Retiring a user removes their identities, so the pair can be linked anew.
 */
export const userIdentities = pgTable(
  "user_identities",
  {
    tenantId: text("tenant_id").notNull(),
    /** The issuer URL, e.g. `https://login.microsoftonline.com/<tid>/v2.0`. */
    issuer: text("issuer").notNull(),
    subject: text("subject").notNull(),
    userId: text("user_id").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.issuer, t.subject] }),
    foreignKey({
      name: "user_identities_user_fk",
      columns: [t.tenantId, t.userId],
      foreignColumns: [users.tenantId, users.id],
    }),
    index("user_identities_user_idx").on(t.tenantId, t.userId),
    check("user_identities_issuer_length", sql`char_length(issuer) between 1 and 1024`),
    check("user_identities_subject_length", sql`char_length(subject) between 1 and 512`),
  ],
);

/**
 * Sign-in sessions (T-102): a person signed in through a provider, holding an opaque cookie
 * `ohs.<tenant>.<session id>.<secret>`. Only a SHA-256 of the secret is kept. A session ends at
 * `expires_at`, after `idle` without use, or when revoked (sign-out, retirement, T-104).
 * Never a service account's: the foreign key names the user's kind, which can't be `service`.
 */
export const sessions = pgTable(
  "sessions",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    userId: text("user_id").notNull(),
    userKind: text("user_kind").notNull(),
    secretHash: text("secret_hash").notNull(),
    /** The configured provider signed in through, and the identity it gave. */
    provider: text("provider").notNull(),
    issuer: text("issuer").notNull(),
    subject: text("subject").notNull(),
    createdAt: createdAt(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
    /** How long it may go unused. */
    idleSeconds: integer("idle_seconds").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: text("revoked_by"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "sessions_user_fk",
      columns: [t.tenantId, t.userId, t.userKind],
      foreignColumns: [users.tenantId, users.id, users.kind],
    }).onUpdate("cascade"),
    // A user's sessions, to end them all.
    index("sessions_user_idx").on(t.tenantId, t.userId),
    // Pruning ended sessions.
    index("sessions_expires_idx").on(t.tenantId, t.expiresAt),
    idCheck("sessions_id_format", "id", "session"),
    check("sessions_person_only", sql`user_kind in ('member', 'guest')`),
    check("sessions_secret_hash_format", sql`secret_hash ~ '^[0-9a-f]{64}$'`),
    check("sessions_provider_format", sql`provider ~ '^[a-z0-9][a-z0-9-]{0,62}$'`),
    check("sessions_issuer_length", sql`char_length(issuer) between 1 and 1024`),
    check("sessions_subject_length", sql`char_length(subject) between 1 and 512`),
    check("sessions_idle_range", sql`idle_seconds between 60 and 2592000`),
    check(
      "sessions_expiry",
      sql`expires_at > created_at and expires_at <= created_at + interval '30 days'`,
    ),
    check(
      "sessions_revocation_complete",
      sql`(revoked_at is null) = (revoked_by is null) and (revoked_at is null or revoked_at >= created_at)`,
    ),
    check(
      "sessions_revoked_by_principal",
      sql`revoked_by is null or revoked_by ~ '^(user|system|scim):.+$'`,
    ),
  ],
);

/** What an API key may be scoped to: core/policy ACTIONS, and zone kinds. */
export const KEY_ACTIONS = ["search", "read", "open", "tag"] as const;
const sqlArray = (values: readonly string[]) =>
  `array[${values.map((v) => `'${v}'`).join(", ")}]::text[]`;

/**
 * API keys (T-111): how a service account authenticates. Only a hash of the secret is kept
 * (the secret is shown once, when the key is issued), and every key is scoped to some actions
 * and zone kinds, expires within a year, and can be revoked. core/identity issues and checks
 * them; a key belongs to a service account, never to a person.
 */
export const apiKeys = pgTable(
  "api_keys",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    userId: text("user_id").notNull(),
    /** Always `service`: with the foreign key, a key can only belong to a service account. */
    userKind: text("user_kind").notNull().default("service"),
    /** Zone ids, when the key is for some zones only (null: every zone of `zones`' kinds). */
    zoneIds: text("zone_ids").array(),
    /** What it is for, as an admin wrote it: "nightly export", "CI". */
    name: text("name").notNull(),
    /** SHA-256 of the secret, hex. The secret is 32 random bytes, so a fast hash is enough. */
    secretHash: text("secret_hash").notNull(),
    actions: text("actions").array().notNull(),
    zones: text("zones").array().notNull(),
    createdBy: text("created_by").notNull(),
    createdAt: createdAt(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: text("revoked_by"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "api_keys_user_fk",
      columns: [t.tenantId, t.userId, t.userKind],
      foreignColumns: [users.tenantId, users.id, users.kind],
    }),
    check("api_keys_service_only", sql`user_kind = 'service'`),
    check(
      "api_keys_zone_ids_valid",
      sql.raw(`zone_ids is null or (cardinality(zone_ids) between 1 and 100
        and array_position(zone_ids, null) is null
        and array_to_string(zone_ids, ',') ~ '^(${idPattern("zone").slice(1, -1)})(,${idPattern("zone").slice(1, -1)})*$')`),
    ),
    // A service account's keys (listing, revoking all at retirement).
    index("api_keys_user_idx").on(t.tenantId, t.userId),
    idCheck("api_keys_id_format", "id", "apiKey"),
    check("api_keys_name_length", sql`char_length(name) between 1 and 200`),
    check("api_keys_secret_hash_format", sql`secret_hash ~ '^[0-9a-f]{64}$'`),
    check(
      "api_keys_actions_valid",
      sql.raw(`cardinality(actions) > 0 and actions <@ ${sqlArray(KEY_ACTIONS)}`),
    ),
    check(
      "api_keys_zones_valid",
      sql.raw(`cardinality(zones) > 0 and zones <@ ${sqlArray(ZONE_KINDS)}`),
    ),
    check(
      "api_keys_expiry",
      sql`expires_at > created_at and expires_at <= created_at + interval '366 days'`,
    ),
    check("api_keys_created_by_principal", sql`created_by ~ '^(user|system):.+$'`),
    check(
      "api_keys_revocation_complete",
      sql`(revoked_at is null) = (revoked_by is null) and (revoked_at is null or revoked_at >= created_at)`,
    ),
    check(
      "api_keys_revoked_by_principal",
      sql`revoked_by is null or revoked_by ~ '^(user|system):.+$'`,
    ),
  ],
);

/**
 * SCIM bearer tokens (T-103): how a tenant's identity provider (Entra's provisioning service)
 * authenticates to `/scim/v2`. Not API keys: a token belongs to the tenant, not to a user, and
 * acts only as that tenant's SCIM client (`scim:<token id>`). The token is
 * `ohscim.<tenant id>.<token id>.<secret>`; only a SHA-256 of the secret is kept. Every token
 * expires within a year and can be revoked; core/identity reads it on every request.
 */
export const scimTokens = pgTable(
  "scim_tokens",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    /** What it is for, as an admin wrote it: "Entra provisioning". */
    name: text("name").notNull(),
    /** SHA-256 of the secret, hex. The secret is 32 random bytes, so a fast hash is enough. */
    secretHash: text("secret_hash").notNull(),
    createdBy: text("created_by").notNull(),
    createdAt: createdAt(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    /** When it last authenticated a request (written at most once a minute). */
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: text("revoked_by"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    idCheck("scim_tokens_id_format", "id", "scimToken"),
    check("scim_tokens_name_length", sql`char_length(name) between 1 and 200`),
    check("scim_tokens_secret_hash_format", sql`secret_hash ~ '^[0-9a-f]{64}$'`),
    check(
      "scim_tokens_expiry",
      sql`expires_at > created_at and expires_at <= created_at + interval '366 days'`,
    ),
    check("scim_tokens_last_used", sql`last_used_at is null or last_used_at >= created_at`),
    check("scim_tokens_created_by_principal", sql`created_by ~ '^(user|system):.+$'`),
    check(
      "scim_tokens_revocation_complete",
      sql`(revoked_at is null) = (revoked_by is null) and (revoked_at is null or revoked_at >= created_at)`,
    ),
    check(
      "scim_tokens_revoked_by_principal",
      sql`revoked_by is null or revoked_by ~ '^(user|system):.+$'`,
    ),
  ],
);

/**
 * A counter per tenant, bumped by a trigger (migration 0021) on every change resolvePrincipal()
 * reads: grants, group memberships, and a user's kind or stops. core/identity's principal cache
 * keys entries by it, so a change anywhere in the tenant invalidates them, in every process.
 */
export const principalEpochs = pgTable("principal_epochs", {
  tenantId: text("tenant_id")
    .primaryKey()
    .references(() => tenants.id),
  epoch: bigint("epoch", { mode: "number" }).notNull().default(0),
});

/** Who is in which group. Direct membership only; nested groups arrive with SCIM (T-103). */
export const groupMembers = pgTable(
  "group_members",
  {
    tenantId: text("tenant_id").notNull(),
    groupId: text("group_id").notNull(),
    userId: text("user_id").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.groupId, t.userId] }),
    foreignKey({
      name: "group_members_group_fk",
      columns: [t.tenantId, t.groupId],
      foreignColumns: [groups.tenantId, groups.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "group_members_user_fk",
      columns: [t.tenantId, t.userId],
      foreignColumns: [users.tenantId, users.id],
    }),
    index("group_members_user_idx").on(t.tenantId, t.userId),
  ],
);

/*
 * Grants (T-602): who may read or write what, as data (spike S3). A grant gives a principal, a
 * user or a group, access to every object carrying a tag, or to one object. Grants expire by
 * default; the expiry is checked when grants are read, so an expired grant stops working the
 * moment it expires, with no job to run. Revoking keeps the row, for "why could X see this?".
 *
 * History has two limits: a grant on an object goes when the object is hard-deleted (objects are
 * normally soft-deleted), and a vocabulary value that was ever granted cannot be deleted, only
 * merged into another (T-406), which carries its grants along.
 */
export const GRANT_ROLES = ["read", "write"] as const;

export const grants = pgTable(
  "grants",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    /** `user:<id>` or `group:<id>`. */
    principal: text("principal").notNull(),
    role: text("role", { enum: GRANT_ROLES }).notNull(),
    /** A tag grant names a facet and value; an object grant names an object. Exactly one. */
    facet: text("facet"),
    value: text("value"),
    objectId: text("object_id"),
    grantedBy: text("granted_by").notNull(),
    createdAt: createdAt(),
    /** Null only for a grant made permanent on purpose. */
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: text("revoked_by"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "grants_tag_fk",
      columns: [t.tenantId, t.facet, t.value],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    foreignKey({
      name: "grants_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    // Loading a caller's grants: by principal, live ones first.
    index("grants_principal_idx").on(t.tenantId, t.principal),
    index("grants_object_idx").on(t.tenantId, t.objectId),
    // "Who can see this?" by tag (T-606), and merging a value (T-406) carrying its grants.
    index("grants_tag_idx")
      .on(t.tenantId, t.facet, t.value)
      .where(sql`facet is not null`),
    idCheck("grants_id_format", "id", "grant"),
    check("grants_principal_format", sql`principal ~ '^(user|group):.+$'`),
    check("grants_role_valid", sql.raw(`role in (${quoted(GRANT_ROLES)})`)),
    check(
      "grants_one_target",
      sql`(facet is not null and value is not null and object_id is null)
       or (facet is null and value is null and object_id is not null)`,
    ),
    check("grants_granted_by_principal", sql`granted_by ~ '^[a-z]+:.+$'`),
    check("grants_expiry_after_creation", sql`expires_at is null or expires_at > created_at`),
    check("grants_revoked_after_creation", sql`revoked_at is null or revoked_at >= created_at`),
    check(
      "grants_revocation_complete",
      sql`(revoked_at is null and revoked_by is null)
       or (revoked_at is not null and revoked_by is not null and revoked_by ~ '^[a-z]+:.+$')`,
    ),
  ],
);

/*
 * The review inbox (T-406). A tag that must not apply on its own waits here instead of in
 * object_tags: a value not yet in the approved vocabulary, a model's low-confidence guess, or a
 * model setting a value that carries visibility or exposure levels. A person approves (the tag
 * applies, reviewed, and a new value joins the vocabulary), rejects, or merges it into an
 * existing value. Resolved items stay, as the record of who decided.
 */
/**
 * `conflict`: a second value of a single-value facet. `primary`: a model proposing which of the
 * object's trusted tags is its home (T-409); an item for that, not for applying a tag.
 */
export const REVIEW_REASONS = [
  "new-value",
  "low-confidence",
  "sensitive",
  "conflict",
  "primary",
] as const;
/** `withdrawn`: a rule's item, closed when the rule stopped giving the tag before anyone decided. */
export const REVIEW_DECISIONS = ["approved", "rejected", "merged", "withdrawn"] as const;

export const tagReviews = pgTable(
  "tag_reviews",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    objectId: text("object_id").notNull(),
    facet: text("facet").notNull(),
    value: text("value").notNull(),
    reason: text("reason", { enum: REVIEW_REASONS }).notNull(),
    source: text("source", { enum: TAG_SOURCES }).notNull(),
    appliedBy: text("applied_by"),
    confidence: real("confidence").notNull(),
    createdAt: createdAt(),
    decision: text("decision", { enum: REVIEW_DECISIONS }),
    /** For a merge: the approved value the tag was applied as instead. */
    mergedInto: text("merged_into"),
    resolvedBy: text("resolved_by"),
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "tag_reviews_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "tag_reviews_value_fk",
      columns: [t.tenantId, t.facet, t.value],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    foreignKey({
      name: "tag_reviews_merged_fk",
      columns: [t.tenantId, t.facet, t.mergedInto],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    // The inbox (listOpenReviews): open items, oldest first, in its exact order.
    index("tag_reviews_open_idx")
      .on(t.tenantId, t.createdAt, t.id)
      .where(sql`resolved_at is null`),
    // Open items for a tag: what approving or merging a value resolves.
    index("tag_reviews_tag_idx")
      .on(t.tenantId, t.facet, t.value)
      .where(sql`resolved_at is null`),
    // An object's items, open or resolved (and the cascade when the object is deleted).
    index("tag_reviews_object_idx").on(t.tenantId, t.objectId),
    // One open item per object and tag, however often it is proposed; and apart from those,
    // one open primary proposal per object.
    uniqueIndex("tag_reviews_one_open")
      .on(t.tenantId, t.objectId, t.facet, t.value)
      .where(sql`resolved_at is null and reason <> 'primary'`),
    uniqueIndex("tag_reviews_one_open_primary")
      .on(t.tenantId, t.objectId)
      .where(sql`resolved_at is null and reason = 'primary'`),
    idCheck("tag_reviews_id_format", "id", "review"),
    check("tag_reviews_reason_valid", sql.raw(`reason in (${quoted(REVIEW_REASONS)})`)),
    check("tag_reviews_source_valid", sql.raw(`source in (${quoted(TAG_SOURCES)})`)),
    check("tag_reviews_confidence_range", sql`confidence >= 0 and confidence <= 1`),
    check(
      "tag_reviews_applied_by_principal",
      sql`applied_by is null or applied_by ~ '^[a-z]+:.+$'`,
    ),
    check(
      "tag_reviews_applied_by_matches_source",
      sql`applied_by is null or starts_with(applied_by, source || ':')`,
    ),
    check(
      "tag_reviews_resolution_complete",
      sql.raw(`(decision is null and resolved_by is null and resolved_at is null and merged_into is null)
       or (decision is not null and decision in (${quoted(REVIEW_DECISIONS)})
           and resolved_by is not null and resolved_by ~ '^[a-z]+:.+$'
           and resolved_at is not null and resolved_at >= created_at
           and (decision = 'merged') = (merged_into is not null))`),
    ),
  ],
);

/** The tag string policy and search use for a facet and value. */
export const tagOf = (facet: string, value: string): string => `${facet}:${value}`;

/**
 * Packs applied to a tenant (T-607): declarative facets, values, defaults, tag rules and Cedar
 * policies. `content` is the pack as applied, the source of its rules and policies; the
 * vocabulary it created lives in facets and facet_values like any other.
 */
export const tenantPacks = pgTable(
  "tenant_packs",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    name: text("name").notNull(),
    version: text("version").notNull(),
    content: jsonb("content").notNull(),
    /** SHA-256 of the pack's canonical JSON, as reviewed. */
    contentHash: text("content_hash").notNull(),
    appliedBy: text("applied_by").notNull(),
    appliedAt: timestamp("applied_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.name] }),
    check("tenant_packs_name_format", sql`name ~ '^[a-z0-9][a-z0-9-]{1,62}[a-z0-9]$'`),
    check("tenant_packs_version_length", sql`char_length(version) between 5 and 64`),
    check("tenant_packs_hash_format", sql`content_hash ~ '^[0-9a-f]{64}$'`),
    check("tenant_packs_applied_by_principal", sql`applied_by ~ '^[a-z]+:.+$'`),
  ],
);

export const ACTIVITY_TYPES = ["view", "open", "edit", "share"] as const;
export const CLIENT_TRUSTS = [
  "first-party",
  "local",
  "commercial",
  "consumer",
] as const satisfies readonly ("first-party" | ClientTrust)[];

/**
 * Activity (T-205): who viewed, opened, edited or shared which file, when, and through which
 * client, for `recent` ("CSV files I opened yesterday", T-506), ranking and the Health Report.
 *
 * It is not the audit log. Audit is the tamper-evident record of every access decision; this is
 * a working index of what people did, so it is prunable (retention), repeat views are merged,
 * and it takes no lock. `origin` says who observed the event: `openhoard` for what OpenHoard
 * served, a connector's source for an edit a crawl found, a feed for imported events (the M365
 * audit feed, T-307), whose own event id goes in `external_id` so a re-import adds nothing.
 *
 * An AI read is a view or open whose client isn't first-party: `client_trust` says which.
 */
export const activityEvents = pgTable(
  "activity_events",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    /** Whole milliseconds, like a JS Date, so a page cursor taken from a row finds its place. */
    at: timestamp("at", { withTimezone: true })
      .notNull()
      .default(sql`date_trunc('milliseconds', now())`),
    /** The principal who acted, e.g. `user:usr_…`. */
    actor: text("actor").notNull(),
    type: text("type").notNull(),
    objectId: text("object_id").notNull(),
    /** The version opened or saved; null for a view, or when the source doesn't say. */
    versionId: text("version_id"),
    /** The client the request came through (an OAuth client id); null when not through one. */
    clientId: text("client_id"),
    clientTrust: text("client_trust"),
    origin: text("origin").notNull().default("openhoard"),
    /** The event's id at its origin, for imported events. */
    externalId: text("external_id"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    // Activity is about files, and goes with them: purging an object removes its activity.
    foreignKey({
      name: "activity_events_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    // A version of that object (with no version, nothing to check).
    foreignKey({
      name: "activity_events_version_fk",
      columns: [t.tenantId, t.objectId, t.versionId],
      foreignColumns: [versions.tenantId, versions.objectId, versions.id],
    }).onDelete("cascade"),
    // recent(): one person's activity, newest first.
    index("activity_events_actor_idx").on(t.tenantId, t.actor, t.at),
    // An object's activity, and the check for a repeat view.
    index("activity_events_object_idx").on(t.tenantId, t.objectId, t.at),
    // Retention prunes by time.
    index("activity_events_at_idx").on(t.tenantId, t.at),
    uniqueIndex("activity_events_external_unique")
      .on(t.tenantId, t.origin, t.externalId)
      .where(sql`external_id is not null`),
    idCheck("activity_events_id_format", "id", "activity"),
    check("activity_events_at_milliseconds", sql`at = date_trunc('milliseconds', at)`),
    check("activity_events_actor_principal", sql`actor ~ '^[a-z]+:.+$'`),
    check("activity_events_type_valid", sql.raw(`type in (${quoted(ACTIVITY_TYPES)})`)),
    check("activity_events_client_complete", sql`(client_id is null) = (client_trust is null)`),
    check(
      "activity_events_client_trust_valid",
      sql.raw(`client_trust is null or client_trust in (${quoted(CLIENT_TRUSTS)})`),
    ),
    check(
      "activity_events_client_id_length",
      sql`client_id is null or char_length(client_id) between 1 and 256`,
    ),
    check("activity_events_origin_format", sql`origin ~ '^[a-z0-9][a-z0-9._-]{0,63}$'`),
    check(
      "activity_events_external_id_length",
      sql`external_id is null or char_length(external_id) between 1 and 512`,
    ),
  ],
);

/** OAuth scopes an MCP client may ask for (T-105), and the policy actions each allows. */
export const OAUTH_SCOPES = ["files:read", "files:tag"] as const;
/** The trust an admin gives an approved AI client: every client trust but first-party. */
export const AI_CLIENT_TRUSTS = ["local", "commercial", "consumer"] as const;

const HEX64 = "^[0-9a-f]{64}$";
const PERSON_KINDS = "user_kind in ('member', 'guest')";

/**
 * OAuth clients a tenant has seen (T-105, T-106): an MCP client people of the tenant tried to
 * connect. `client_key` is a SHA-256 of what identifies the client: its Client ID Metadata
 * Document URL (`cimd`), or its redirect URIs (`dcr`, dynamically registered, which OpenHoard
 * keeps no record of). A client gets tokens only once an admin approved it, with a trust label.
 */
export const oauthClients = pgTable(
  "oauth_clients",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    clientKey: text("client_key").notNull(),
    kind: text("kind").notNull(),
    /** What people and admins see as its id: the metadata URL, or `dcr:<key prefix>`. */
    clientRef: text("client_ref").notNull(),
    /** As the client says: never trusted for anything but display. */
    name: text("name").notNull(),
    redirectUris: text("redirect_uris").array().notNull(),
    status: text("status").notNull().default("pending"),
    trust: text("trust"),
    requestedBy: text("requested_by").notNull(),
    requestedAt: timestamp("requested_at", { withTimezone: true }).notNull().defaultNow(),
    decidedBy: text("decided_by"),
    decidedAt: timestamp("decided_at", { withTimezone: true }),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.clientKey] }),
    check("oauth_clients_key_format", sql.raw(`client_key ~ '${HEX64}'`)),
    check("oauth_clients_kind_valid", sql`kind in ('cimd', 'dcr')`),
    check("oauth_clients_ref_length", sql`char_length(client_ref) between 1 and 2048`),
    check("oauth_clients_name_length", sql`char_length(name) between 1 and 200`),
    check(
      "oauth_clients_redirects",
      sql`cardinality(redirect_uris) between 1 and 20 and array_position(redirect_uris, null) is null`,
    ),
    check("oauth_clients_status_valid", sql`status in ('pending', 'approved', 'refused')`),
    check(
      "oauth_clients_trust",
      sql.raw(
        `(status = 'approved') = (trust is not null) and (trust is null or trust in (${quoted(AI_CLIENT_TRUSTS)}))`,
      ),
    ),
    check(
      "oauth_clients_decision",
      sql`(status = 'pending') = (decided_at is null) and (decided_at is null) = (decided_by is null)`,
    ),
    check("oauth_clients_requested_by", sql`requested_by ~ '^(user|system):.+$'`),
    check("oauth_clients_decided_by", sql`decided_by is null or decided_by ~ '^(user|system):.+$'`),
  ],
);

const scopesCheck = (name: string) =>
  check(
    name,
    sql.raw(
      `cardinality(scopes) between 1 and ${OAUTH_SCOPES.length} and scopes <@ ${sqlArray(OAUTH_SCOPES)}`,
    ),
  );

/**
 * Authorization codes (T-105): a person consented, and the client gets a code for tokens. Used
 * once, within a minute, by the client it was for, at the redirect URI it went to, with the PKCE
 * verifier behind `code_challenge`. A code used twice revokes the grant it made.
 */
export const oauthCodes = pgTable(
  "oauth_codes",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    secretHash: text("secret_hash").notNull(),
    userId: text("user_id").notNull(),
    userKind: text("user_kind").notNull(),
    clientKey: text("client_key").notNull(),
    redirectUri: text("redirect_uri").notNull(),
    /** base64url SHA-256 of the verifier (S256, the only method). */
    codeChallenge: text("code_challenge").notNull(),
    scopes: text("scopes").array().notNull(),
    resource: text("resource").notNull(),
    createdAt: createdAt(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    /** The grant it made, to revoke when the code is replayed. */
    grantId: text("grant_id"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "oauth_codes_user_fk",
      columns: [t.tenantId, t.userId, t.userKind],
      foreignColumns: [users.tenantId, users.id, users.kind],
    }).onUpdate("cascade"),
    foreignKey({
      name: "oauth_codes_client_fk",
      columns: [t.tenantId, t.clientKey],
      foreignColumns: [oauthClients.tenantId, oauthClients.clientKey],
    }),
    index("oauth_codes_expires_idx").on(t.tenantId, t.expiresAt),
    // Pruning a grant checks no code still points at it.
    index("oauth_codes_grant_idx").on(t.tenantId, t.grantId),
    idCheck("oauth_codes_id_format", "id", "oauthCode"),
    check("oauth_codes_person_only", sql.raw(PERSON_KINDS)),
    check("oauth_codes_secret_hash_format", sql.raw(`secret_hash ~ '${HEX64}'`)),
    check("oauth_codes_redirect_length", sql`char_length(redirect_uri) between 1 and 2048`),
    check("oauth_codes_challenge_format", sql`code_challenge ~ '^[A-Za-z0-9_-]{43}$'`),
    scopesCheck("oauth_codes_scopes"),
    check("oauth_codes_resource_length", sql`char_length(resource) between 1 and 2048`),
    check(
      "oauth_codes_expiry",
      sql`expires_at > created_at and expires_at <= created_at + interval '10 minutes'`,
    ),
    check("oauth_codes_used", sql`used_at is null or used_at >= created_at`),
  ],
);

/**
 * What a person let a client do (T-105): the scopes, for one resource (the MCP server), until
 * `expires_at` or revocation. The client holds a refresh token for it, rotated on every use; a
 * refresh token used again after it was rotated revokes the grant (it was stolen or replayed).
 */
export const oauthGrants = pgTable(
  "oauth_grants",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    userId: text("user_id").notNull(),
    userKind: text("user_kind").notNull(),
    clientKey: text("client_key").notNull(),
    scopes: text("scopes").array().notNull(),
    resource: text("resource").notNull(),
    refreshHash: text("refresh_hash").notNull(),
    /** The refresh token before the current one: presenting it again means a replay. */
    previousRefreshHash: text("previous_refresh_hash"),
    createdAt: createdAt(),
    refreshedAt: timestamp("refreshed_at", { withTimezone: true }),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: text("revoked_by"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "oauth_grants_user_fk",
      columns: [t.tenantId, t.userId, t.userKind],
      foreignColumns: [users.tenantId, users.id, users.kind],
    }).onUpdate("cascade"),
    foreignKey({
      name: "oauth_grants_client_fk",
      columns: [t.tenantId, t.clientKey],
      foreignColumns: [oauthClients.tenantId, oauthClients.clientKey],
    }),
    // A person's grants (to revoke them all), a client's (when an admin refuses it).
    index("oauth_grants_user_idx").on(t.tenantId, t.userId),
    index("oauth_grants_client_idx").on(t.tenantId, t.clientKey),
    idCheck("oauth_grants_id_format", "id", "oauthGrant"),
    check("oauth_grants_person_only", sql.raw(PERSON_KINDS)),
    scopesCheck("oauth_grants_scopes"),
    check("oauth_grants_resource_length", sql`char_length(resource) between 1 and 2048`),
    check(
      "oauth_grants_refresh_format",
      sql.raw(
        `refresh_hash ~ '${HEX64}' and (previous_refresh_hash is null or previous_refresh_hash ~ '${HEX64}')`,
      ),
    ),
    check(
      "oauth_grants_expiry",
      sql`expires_at > created_at and expires_at <= created_at + interval '90 days'`,
    ),
    check(
      "oauth_grants_revocation_complete",
      sql`(revoked_at is null) = (revoked_by is null) and (revoked_at is null or revoked_at >= created_at)`,
    ),
    check(
      "oauth_grants_revoked_by_principal",
      sql`revoked_by is null or revoked_by ~ '^(user|system|scim):.+$'`,
    ),
  ],
);

/** Access tokens (T-105): short-lived, one grant's, checked on every request. */
export const oauthTokens = pgTable(
  "oauth_tokens",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    grantId: text("grant_id").notNull(),
    secretHash: text("secret_hash").notNull(),
    /** The grant's scopes, or fewer when the client asked for fewer at refresh. */
    scopes: text("scopes").array().notNull(),
    createdAt: createdAt(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    scopesCheck("oauth_tokens_scopes"),
    foreignKey({
      name: "oauth_tokens_grant_fk",
      columns: [t.tenantId, t.grantId],
      foreignColumns: [oauthGrants.tenantId, oauthGrants.id],
    }).onDelete("cascade"),
    index("oauth_tokens_grant_idx").on(t.tenantId, t.grantId),
    index("oauth_tokens_expires_idx").on(t.tenantId, t.expiresAt),
    idCheck("oauth_tokens_id_format", "id", "oauthToken"),
    check("oauth_tokens_secret_hash_format", sql.raw(`secret_hash ~ '${HEX64}'`)),
    check(
      "oauth_tokens_expiry",
      sql`expires_at > created_at and expires_at <= created_at + interval '1 day'`,
    ),
  ],
);

/*
 * Audit (T-701): one append-only, hash-chained log per tenant, in its own schema. core/audit
 * appends and verifies; the chain rules are in core/audit/src/chain.ts.
 *
 * `event` is the exact canonical JSON the hash covers, so verification never depends on how the
 * database round-trips a type. The other columns repeat its fields for queries and exports.
 * Rows can be read and inserted in their tenant, never changed: see 0005_audit_rls.sql. Every
 * insert must extend the chain with a row that checks out (0017_audit_check_event.sql).
 */
export const auditSchema = pgSchema("audit");

const HASH = "^[0-9a-f]{64}$";

export const auditEvents = auditSchema.table(
  "events",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    seq: bigint("seq", { mode: "number" }).notNull(),
    at: timestamp("at", { withTimezone: true }).notNull(),
    actor: text("actor").notNull(),
    action: text("action").notNull(),
    decision: text("decision", { enum: ["allow", "deny"] }).notNull(),
    client: text("client"),
    object: text("object"),
    version: text("version"),
    event: text("event").notNull(),
    prevHash: text("prev_hash").notNull(),
    hash: text("hash").notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.seq] }),
    // Exports filter by time, actor and object (T-703).
    index("audit_events_at_idx").on(t.tenantId, t.at),
    index("audit_events_object_idx").on(t.tenantId, t.object),
    index("audit_events_actor_idx").on(t.tenantId, t.actor, t.seq),
    check("audit_events_seq_positive", sql`seq > 0`),
    check("audit_events_decision_valid", sql`decision in ('allow', 'deny')`),
    check("audit_events_hash_format", sql.raw(`hash ~ '${HASH}' and prev_hash ~ '${HASH}'`)),
  ],
);

/** Every table in the public schema, for tests and tooling that must cover all of them. */
export const tables = {
  tenants,
  zones,
  blobs,
  objects,
  versions,
  sourceRefs,
  facets,
  facetValues,
  objectTags,
  grants,
  tagReviews,
  users,
  userIdentities,
  groups,
  groupMembers,
  tenantPacks,
  principalEpochs,
  apiKeys,
  activityEvents,
  sessions,
  oauthClients,
  oauthCodes,
  oauthGrants,
  oauthTokens,
  scimTokens,
} as const;
