import { sql } from "drizzle-orm";
import { EXPOSURE, VISIBILITY } from "@openhoard/core-policy";
import {
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  pgSchema,
  pgTable,
  primaryKey,
  real,
  text,
  timestamp,
  unique,
} from "drizzle-orm/pg-core";
import { idPattern, type IdKind } from "./ids.js";

/*
 * The catalog's core tables (T-201). Conventions, which the tests in schema.test.ts and
 * rls.test.ts enforce:
 *
 * - Every table has `tenant_id` (the tenants table has `id`) and forced row-level security that
 *   matches it against `app.tenant_id`; see migrations/0001_tenant_rls.sql and database.ts.
 * - Primary keys and foreign keys include `tenant_id`, so a row can only ever reference rows of
 *   its own tenant. This holds even for code that runs without row-level security.
 * - Nothing cascades from a tenant, a zone or a blob. Removing a tenant's data is a deliberate,
 *   audited process (legal holds apply), never the side effect of one DELETE. Deleting an object
 *   does remove its versions and source references.
 * - Ids are generated by the application (ids.ts) and checked here, so a malformed or misplaced
 *   id fails loudly.
 * - Timestamps are `timestamptz`, read as Date objects; every connection runs in UTC.
 * - `bigint` columns use `mode: "number"` where values stay far below 2^53 (byte sizes).
 *
 * Changing this file? Run `pnpm --filter @openhoard/core-db db:generate` and commit the new
 * migration. CI fails when the schema and the migrations disagree.
 */

const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const idCheck = (name: string, column: string, kind: IdKind) =>
  check(name, sql.raw(`${column} ~ '${idPattern(kind)}'`));

/** An organization. Everything else belongs to exactly one tenant. */
export const tenants = pgTable(
  "tenants",
  {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    createdAt: createdAt(),
  },
  () => [
    idCheck("tenants_id_format", "id", "tenant"),
    check("tenants_name_length", sql`char_length(name) between 1 and 200`),
  ],
);

/** Where objects live and which rules apply to them (ADR and PRD: Managed, Indexed, Local-only, Code). */
export const zones = pgTable(
  "zones",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    kind: text("kind", { enum: ["managed", "indexed", "local-only", "code"] }).notNull(),
    name: text("name").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    unique("zones_name_unique").on(t.tenantId, t.name),
    idCheck("zones_id_format", "id", "zone"),
    check("zones_kind_valid", sql`kind in ('managed', 'indexed', 'local-only', 'code')`),
    check("zones_name_length", sql`char_length(name) between 1 and 200`),
  ],
);

/**
 * Immutable content, identified by its tenant-scoped BLAKE3 id (`b3t:…`, ADR-0013 and
 * core/catalog `scopedBlobId`). Identical bytes in one tenant are one blob; the raw content hash
 * is never stored, so the database cannot link identical files across tenants either.
 */
export const blobs = pgTable(
  "blobs",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    size: bigint("size", { mode: "number" }).notNull(),
    /** Storage key when OpenHoard holds the bytes (managed zones); null for index-only content. */
    location: text("location"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    check("blobs_id_format", sql`id ~ '^b3t:[0-9a-f]{64}$'`),
    check("blobs_size_nonnegative", sql`size >= 0`),
  ],
);

/** The logical file: what people and agents find, tag and share. */
export const objects = pgTable(
  "objects",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    zoneId: text("zone_id").notNull(),
    title: text("title").notNull(),
    /** Principal that owns the object, e.g. `user:…`; identities arrive with E1 (T-101). */
    ownerId: text("owner_id").notNull(),
    createdAt: createdAt(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    /** Set when the source deletes the file; rows are kept for audit and undo. */
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "objects_zone_fk",
      columns: [t.tenantId, t.zoneId],
      foreignColumns: [zones.tenantId, zones.id],
    }),
    index("objects_zone_idx").on(t.tenantId, t.zoneId),
    idCheck("objects_id_format", "id", "object"),
    check("objects_title_length", sql`char_length(title) between 1 and 1024`),
    check("objects_owner_principal", sql`owner_id ~ '^[a-z]+:.+$'`),
  ],
);

/** One saved state of an object, pointing at an immutable blob. */
export const versions = pgTable(
  "versions",
  {
    tenantId: text("tenant_id").notNull(),
    id: text("id").notNull(),
    objectId: text("object_id").notNull(),
    /** 1, 2, 3… per object. */
    seq: integer("seq").notNull(),
    blobId: text("blob_id").notNull(),
    /** Media type essence in lower case, without parameters: `text/csv`, not `text/csv; charset=…`. */
    mime: text("mime").notNull(),
    /** Principal that saved this version, when the source says. */
    authorId: text("author_id"),
    /** The source's own version marker (e.g. a SharePoint cTag), to skip unchanged files. */
    sourceVersion: text("source_version"),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    unique("versions_seq_unique").on(t.tenantId, t.objectId, t.seq),
    foreignKey({
      name: "versions_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "versions_blob_fk",
      columns: [t.tenantId, t.blobId],
      foreignColumns: [blobs.tenantId, blobs.id],
    }),
    index("versions_blob_idx").on(t.tenantId, t.blobId),
    idCheck("versions_id_format", "id", "version"),
    check("versions_seq_positive", sql`seq > 0`),
    check(
      "versions_mime_format",
      sql`mime ~ '^[a-z0-9][a-z0-9!#$&^_.+-]*/[a-z0-9][a-z0-9!#$&^_.+-]*$'`,
    ),
    check("versions_author_principal", sql`author_id is null or author_id ~ '^[a-z]+:.+$'`),
  ],
);

/**
 * Where an object comes from outside OpenHoard: a SharePoint drive item, a bucket key, a path.
 * `source` names the configured connection (connector instances arrive with E3, T-301); the
 * pair (source, external_id) identifies the item there, so re-crawls find the same object.
 */
export const sourceRefs = pgTable(
  "source_refs",
  {
    tenantId: text("tenant_id").notNull(),
    source: text("source").notNull(),
    externalId: text("external_id").notNull(),
    objectId: text("object_id").notNull(),
    url: text("url"),
    /** The source's change marker for the item (e.g. an eTag), for delta sync. */
    etag: text("etag"),
    syncedAt: timestamp("synced_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.source, t.externalId] }),
    foreignKey({
      name: "source_refs_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    index("source_refs_object_idx").on(t.tenantId, t.objectId),
    check("source_refs_source_format", sql`source ~ '^[a-z0-9][a-z0-9._-]{0,63}$'`),
    check("source_refs_external_id_length", sql`char_length(external_id) between 1 and 2048`),
  ],
);

/*
 * Tags (T-202). A tag is `facet:value`, e.g. `client:acme` or `sensitivity:restricted`. The
 * vocabulary (facets and their values) belongs to the tenant; values carry the visibility and
 * exposure levels core/policy resolves per object. Both parts are ASCII slugs, so a tag can sit
 * inside a principal (`tag:client:acme`) and compare the same on every engine (spike S2).
 */

const quoted = (values: readonly string[]) => values.map((v) => `'${v}'`).join(", ");
const SLUG = "^[a-z0-9][a-z0-9._-]{0,127}$";

/** A dimension of the vocabulary: client, project, sensitivity, department… */
export const facets = pgTable(
  "facets",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    key: text("key").notNull(),
    label: text("label").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.key] }),
    check("facets_key_format", sql`key ~ '^[a-z][a-z0-9-]{0,63}$'`),
    check("facets_label_length", sql`char_length(label) between 1 and 200`),
  ],
);

/**
 * One value of a facet. Proposed values (by a model, an agent or a user) start unapproved and
 * wait in the review inbox (T-406); nothing creates approved vocabulary implicitly.
 */
export const facetValues = pgTable(
  "facet_values",
  {
    tenantId: text("tenant_id").notNull(),
    facet: text("facet").notNull(),
    value: text("value").notNull(),
    label: text("label").notNull(),
    approved: boolean("approved").notNull().default(false),
    /** Null: this value sets no visibility; the object's other tags or the tenant default do. */
    visibility: text("visibility", { enum: VISIBILITY }),
    /** Null: this value sets no exposure level. */
    exposure: text("exposure", { enum: EXPOSURE }),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.facet, t.value] }),
    foreignKey({
      name: "facet_values_facet_fk",
      columns: [t.tenantId, t.facet],
      foreignColumns: [facets.tenantId, facets.key],
    }),
    check("facet_values_value_format", sql.raw(`value ~ '${SLUG}'`)),
    check("facet_values_label_length", sql`char_length(label) between 1 and 200`),
    check(
      "facet_values_visibility_valid",
      sql.raw(`visibility is null or visibility in (${quoted(VISIBILITY)})`),
    ),
    check(
      "facet_values_exposure_valid",
      sql.raw(`exposure is null or exposure in (${quoted(EXPOSURE)})`),
    ),
  ],
);

export const TAG_SOURCES = ["rule", "model", "user", "pack"] as const;

/** A tag on an object, with where it came from and whether a person has confirmed it. */
export const objectTags = pgTable(
  "object_tags",
  {
    tenantId: text("tenant_id").notNull(),
    objectId: text("object_id").notNull(),
    facet: text("facet").notNull(),
    value: text("value").notNull(),
    /** What applied it: a rule, a model, a person, or a pack. */
    source: text("source", { enum: TAG_SOURCES }).notNull(),
    /** Who or what exactly, when known: `user:…`, `model:…`, `rule:…`, `pack:…`. */
    appliedBy: text("applied_by"),
    /** 1 for rules, people and packs; the model's score otherwise. */
    confidence: real("confidence").notNull(),
    reviewed: boolean("reviewed").notNull().default(false),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.objectId, t.facet, t.value] }),
    foreignKey({
      name: "object_tags_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    foreignKey({
      name: "object_tags_value_fk",
      columns: [t.tenantId, t.facet, t.value],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    // Finding objects by tag: the search filter and "who can see this" (T-504, T-606).
    index("object_tags_tag_idx").on(t.tenantId, t.facet, t.value),
    check("object_tags_source_valid", sql.raw(`source in (${quoted(TAG_SOURCES)})`)),
    check("object_tags_confidence_range", sql`confidence >= 0 and confidence <= 1`),
    check(
      "object_tags_applied_by_principal",
      sql`applied_by is null or applied_by ~ '^[a-z]+:.+$'`,
    ),
  ],
);

/*
 * Grants (T-602): who may read or write what, as data (spike S3). A grant gives a principal, a
 * user or a group, access to every object carrying a tag, or to one object. Grants expire by
 * default; the expiry is checked when grants are read, so an expired grant stops working the
 * moment it expires, with no job to run. Revoking keeps the row, for "why could X see this?".
 *
 * History has two limits: a grant on an object goes when the object is hard-deleted (objects are
 * normally soft-deleted), and a vocabulary value that was ever granted cannot be deleted, only
 * merged into another (T-406), which carries its grants along.
 */
export const GRANT_ROLES = ["read", "write"] as const;

export const grants = pgTable(
  "grants",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    id: text("id").notNull(),
    /** `user:<id>` or `group:<id>`. */
    principal: text("principal").notNull(),
    role: text("role", { enum: GRANT_ROLES }).notNull(),
    /** A tag grant names a facet and value; an object grant names an object. Exactly one. */
    facet: text("facet"),
    value: text("value"),
    objectId: text("object_id"),
    grantedBy: text("granted_by").notNull(),
    createdAt: createdAt(),
    /** Null only for a grant made permanent on purpose. */
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    revokedBy: text("revoked_by"),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.id] }),
    foreignKey({
      name: "grants_tag_fk",
      columns: [t.tenantId, t.facet, t.value],
      foreignColumns: [facetValues.tenantId, facetValues.facet, facetValues.value],
    }),
    foreignKey({
      name: "grants_object_fk",
      columns: [t.tenantId, t.objectId],
      foreignColumns: [objects.tenantId, objects.id],
    }).onDelete("cascade"),
    // Loading a caller's grants: by principal, live ones first.
    index("grants_principal_idx").on(t.tenantId, t.principal),
    index("grants_object_idx").on(t.tenantId, t.objectId),
    idCheck("grants_id_format", "id", "grant"),
    check("grants_principal_format", sql`principal ~ '^(user|group):.+$'`),
    check("grants_role_valid", sql.raw(`role in (${quoted(GRANT_ROLES)})`)),
    check(
      "grants_one_target",
      sql`(facet is not null and value is not null and object_id is null)
       or (facet is null and value is null and object_id is not null)`,
    ),
    check("grants_granted_by_principal", sql`granted_by ~ '^[a-z]+:.+$'`),
    check("grants_expiry_after_creation", sql`expires_at is null or expires_at > created_at`),
    check("grants_revoked_after_creation", sql`revoked_at is null or revoked_at >= created_at`),
    check(
      "grants_revocation_complete",
      sql`(revoked_at is null and revoked_by is null)
       or (revoked_at is not null and revoked_by is not null and revoked_by ~ '^[a-z]+:.+$')`,
    ),
  ],
);

/** The tag string policy and search use for a facet and value. */
export const tagOf = (facet: string, value: string): string => `${facet}:${value}`;

/*
 * Audit (T-701): one append-only, hash-chained log per tenant, in its own schema. core/audit
 * appends and verifies; the chain rules are in core/audit/src/chain.ts.
 *
 * `event` is the exact canonical JSON the hash covers, so verification never depends on how the
 * database round-trips a type. The other columns repeat its fields for queries and exports.
 * Rows can be read and inserted in their tenant, never changed: see 0005_audit_rls.sql.
 */
export const auditSchema = pgSchema("audit");

const HASH = "^[0-9a-f]{64}$";

export const auditEvents = auditSchema.table(
  "events",
  {
    tenantId: text("tenant_id")
      .notNull()
      .references(() => tenants.id),
    seq: bigint("seq", { mode: "number" }).notNull(),
    at: timestamp("at", { withTimezone: true }).notNull(),
    actor: text("actor").notNull(),
    action: text("action").notNull(),
    decision: text("decision", { enum: ["allow", "deny"] }).notNull(),
    client: text("client"),
    object: text("object"),
    version: text("version"),
    event: text("event").notNull(),
    prevHash: text("prev_hash").notNull(),
    hash: text("hash").notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.tenantId, t.seq] }),
    // Exports filter by time, actor and object (T-703).
    index("audit_events_at_idx").on(t.tenantId, t.at),
    index("audit_events_object_idx").on(t.tenantId, t.object),
    check("audit_events_seq_positive", sql`seq > 0`),
    check("audit_events_decision_valid", sql`decision in ('allow', 'deny')`),
    check("audit_events_hash_format", sql.raw(`hash ~ '${HASH}' and prev_hash ~ '${HASH}'`)),
  ],
);

/** Every table in the public schema, for tests and tooling that must cover all of them. */
export const tables = {
  tenants,
  zones,
  blobs,
  objects,
  versions,
  sourceRefs,
  facets,
  facetValues,
  objectTags,
  grants,
} as const;
